name: Scrape AnimeTosho Comments

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:
    inputs:
      keywords:
        description: 'Keywords to filter by (e.g., "[EMBER], [SubsPlease]")'
        required: false
        type: string
      dump_comments:
        description: 'Initialize database without sending notifications'
        required: false
        type: boolean
      upload_db:
        description: 'Upload encrypted database to Catbox Litterbox'
        required: false
        type: boolean
      db_expiry:
        description: 'Expiry time for database upload'
        required: false
        type: choice
        options:
          - 1h
          - 12h
          - 24h
          - 72h
        default: '12h'

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: |
          python comment_scraper.py https://animetosho.org/comments \
            --webhook "${{ secrets.DISCORD_WEBHOOK_URL }}" \
            --secret-webhook "${{ secrets.DISCORD_SECRET_WEBHOOK_URL }}" \
            ${{ github.event.inputs.keywords && format('--keyword {0}', join(split(github.event.inputs.keywords, ', '), ' --keyword ')) || '' }} \
            ${{ github.event.inputs.dump_comments == 'true' && '--dump-comments' || '' }} \
            ${{ github.event.inputs.upload_db == 'true' && '--upload-db' || '' }} \
            --db-expiry ${{ github.event.inputs.db_expiry || '12h' }}
